"""
RehabSense AI dashboard — enhanced with:
  - Anomaly detection (Isolation Forest) — flags outlier sessions per patient
  - Recovery trajectory prediction — ROM projection with dashed Plotly line
  - LLM-generated patient summary (Google Gemini)
  - FHIR R4 JSON export
  - Pain/fatigue correlation view

Run:  streamlit run dashboard/app.py

Reads from the SQLite DB that main.py writes to — run a session or two
with main.py first so there's data to show.
"""

import sys, json, os
from pathlib import Path
sys.path.append(str(Path(__file__).resolve().parents[1]))

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

from src.database import db
from src.ml.anomaly import AnomalyDetector
from src.ml.trajectory import predict_trajectory
from config.exercise_config import EXERCISES

st.set_page_config(page_title="RehabSense AI", layout="wide")
db.init_db()

# ── Gemini helper ────────────────────────────────────────────────────────────
GEMINI_KEY = os.environ.get("GEMINI_API_KEY", "")

def llm_summary(sessions_df: pd.DataFrame, patient_id: str) -> str:
    """Generate a one-paragraph clinical summary using Gemini. Gracefully degrades."""
    avg_rom   = round(sessions_df["rom"].mean(), 1)
    avg_score = round(sessions_df["rehab_score"].mean(), 1)
    trend = "improving" if len(sessions_df) >= 2 and sessions_df["rehab_score"].iloc[-1] > sessions_df["rehab_score"].iloc[0] else "declining"

    # Fallback summary (shown when no key or API error)
    fallback = (f"Patient {patient_id} has completed {len(sessions_df)} sessions. "
                f"Average ROM: {avg_rom}°. Average rehabilitation score: {avg_score}/100. "
                f"Overall trend is {trend}.")

    if not GEMINI_KEY:
        return fallback + " (Set GEMINI_API_KEY env var for AI-generated summaries.)"

    try:
        import google.generativeai as genai
        genai.configure(api_key=GEMINI_KEY)
        model = genai.GenerativeModel("gemini-3.6-flash")
        history = "; ".join(
            f"Session {i+1}: {r.exercise_name}, ROM {r.rom}°, score {r.rehab_score}"
            for i, r in enumerate(sessions_df.itertuples())
        )
        prompt = (f"You are a rehabilitation report assistant. Write one concise paragraph "
                  f"(3-4 sentences) summarising this patient's rehabilitation history for a "
                  f"physiotherapist's clinical report. Be objective and specific with numbers. "
                  f"Do not give diagnoses.\nSession history: {history}")
        response = model.generate_content(prompt)
        return response.text
    except Exception as e:
        return fallback + f" (AI summary error: {e})"


# ── FHIR export helper ────────────────────────────────────────────────────────
def sessions_to_fhir(sessions_df: pd.DataFrame, patient_id: str) -> str:
    resources = []
    for i, row in enumerate(sessions_df.itertuples()):
        resources.append({
            "resourceType": "Observation",
            "id": f"rehabsense-obs-{i+1}",
            "status": "final",
            "category": [{"coding": [{"system": "http://terminology.hl7.org/CodeSystem/observation-category",
                                       "code": "activity", "display": "Activity"}]}],
            "code": {"coding": [{"system": "http://loinc.org", "code": "80319-7",
                                  "display": "Range of motion of joint"}],
                     "text": f"Rehabilitation session — {row.exercise_name}"},
            "subject": {"reference": f"Patient/{patient_id}"},
            "effectiveDateTime": row.date,
            "valueQuantity": {"value": float(row.rom), "unit": "degrees",
                              "system": "http://unitsofmeasure.org", "code": "deg"},
            "component": [
                {"code": {"text": "Rehabilitation Score"}, "valueQuantity": {"value": float(row.rehab_score)}},
                {"code": {"text": "Correct Repetitions"}, "valueQuantity": {"value": int(row.correct_reps)}},
            ],
            "note": [{"text": "Generated by RehabSense AI — wellness monitoring prototype, not a diagnostic device."}],
        })
    bundle = {"resourceType": "Bundle", "type": "collection",
              "entry": [{"resource": r} for r in resources]}
    return json.dumps(bundle, indent=2)


# ═════════════════════════════════════════════════════════════════════════════
st.title("🦾 RehabSense AI")
st.caption(
    "AI-assisted rehabilitation monitoring prototype. "
    "This is not a medical device and does not provide diagnoses.\n"
    "**Privacy:** All pose processing runs client-side — no video ever leaves the device."
)

tab_patient, tab_therapist = st.tabs(["Patient View", "Physiotherapist View"])

# ──────────────────────────────────────────── PATIENT TAB
with tab_patient:
    patients = db.get_all_patients()
    patient_ids = [p["patient_id"] for p in patients] or ["P001"]
    selected_patient = st.selectbox("Select patient", patient_ids, key="patient_select")

    sessions = db.get_sessions_for_patient(selected_patient)

    if not sessions:
        st.info(f"No sessions recorded yet. Run `python main.py --patient {selected_patient}` to record a live session.")
    else:
        df = pd.DataFrame(sessions)
        latest = df.iloc[-1]

        col1, col2, col3, col4 = st.columns(4)
        col1.metric("Latest Rehab Score",    f"{latest['rehab_score']}/100")
        col2.metric("Latest ROM",            f"{latest['rom']}°")
        col3.metric("Correct Reps",          f"{latest['correct_reps']}/{latest['total_reps']}")
        col4.metric("Movement Quality",      f"{latest['movement_score']}%")

        # ── Recovery trajectory ──────────────────────────────────────────────
        st.subheader("📈 ROM Progress & Recovery Trajectory")
        df["session_number"] = range(1, len(df) + 1)
        traj = predict_trajectory(df)

        fig = go.Figure()
        # Actual ROM line
        fig.add_scatter(x=df["session_number"], y=df["rom"], mode="lines+markers",
                        name="Actual ROM (°)", line=dict(color="#22D3AA", width=2.5), marker=dict(size=8))
        # Fitted trendline
        if not traj["not_enough_data"]:
            fig.add_scatter(x=traj["_x"], y=traj["_y_fit"], mode="lines",
                            name="Trend fit", line=dict(color="#3B82F6", width=1.5, dash="dot"))
            # Future projection
            future_x = [df["session_number"].iloc[-1] + i for i in range(1, len(traj["_y_future"]) + 1)]
            fig.add_scatter(x=future_x, y=traj["_y_future"], mode="lines",
                            name="Projected ROM", line=dict(color="#F59E0B", width=2, dash="dash"))

        fig.update_layout(title="ROM Trend & 4-Week Projection",
                          xaxis_title="Session", yaxis_title="ROM (°)",
                          plot_bgcolor="rgba(0,0,0,0)", paper_bgcolor="rgba(0,0,0,0)",
                          font=dict(color="#E8EEF6"), legend=dict(bgcolor="rgba(0,0,0,0)"))
        st.plotly_chart(fig, use_container_width=True)

        if not traj["not_enough_data"]:
            t1, t2, t3 = st.columns(3)
            icon = "✅" if traj["on_track"] else "⚠️"
            t1.metric(f"{icon} Projected ROM (2 wks)", f"{traj['projected_rom']}°")
            t2.metric("Projected ROM (4 wks)", f"{traj['projected_rom_4w']}°")
            t3.metric("Trend", f"{traj['trend_slope']:+.1f}°/session")
            st.info(f"🤖 **Trajectory:** {traj['message']}")

        # ── Rehab score trend ────────────────────────────────────────────────
        st.subheader("Progress Over Sessions")
        fig2 = px.line(df, x="session_number", y=["rehab_score"],
                       markers=True, labels={"value": "Score", "session_number": "Session"},
                       title="Rehabilitation Score Trend")
        st.plotly_chart(fig2, use_container_width=True)

        st.subheader("Session History")
        st.dataframe(
            df[["date", "exercise_name", "total_reps", "correct_reps", "incorrect_reps",
                "rom", "movement_score", "rehab_score"]],
            use_container_width=True,
        )

        # ── FHIR Export ──────────────────────────────────────────────────────
        st.subheader("📋 Export")
        fhir_json = sessions_to_fhir(df, selected_patient)
        col_csv, col_fhir = st.columns(2)
        with col_csv:
            csv = df.to_csv(index=False)
            st.download_button("⬇ Download CSV", csv,
                               file_name=f"rehabsense_{selected_patient}.csv", mime="text/csv")
        with col_fhir:
            st.download_button("🔗 Download FHIR R4 JSON", fhir_json,
                               file_name=f"rehabsense_{selected_patient}_fhir.json",
                               mime="application/json",
                               help="FHIR R4 Observation bundle — interoperability-ready export")


# ──────────────────────────────────────────── THERAPIST TAB
with tab_therapist:
    patients = db.get_all_patients()
    if not patients:
        st.info("No patients yet.")
    else:
        for p in patients:
            with st.expander(f"Patient: {p['patient_id']}", expanded=False):
                sessions = db.get_sessions_for_patient(p["patient_id"])
                if not sessions:
                    st.write("No sessions yet.")
                    continue

                df = pd.DataFrame(sessions)
                df["session_number"] = range(1, len(df) + 1)

                # ── Anomaly detection ────────────────────────────────────────
                detector = AnomalyDetector()
                detector.fit(df)
                anomaly_status = detector.status()

                if anomaly_status["ready"]:
                    df["is_anomaly"] = df.apply(lambda row: detector.is_anomaly(row.to_dict()), axis=1)
                    df["anomaly_score"] = df.apply(lambda row: round(detector.score(row.to_dict()), 3), axis=1)
                    n_anomalies = df["is_anomaly"].sum()
                    if n_anomalies > 0:
                        st.warning(f"🤖 Anomaly Detection: **{n_anomalies} session(s)** flagged as statistically unusual vs this patient's baseline.")
                    else:
                        st.success("🤖 Anomaly Detection: All sessions within normal range for this patient.")
                else:
                    st.info(f"🤖 Anomaly Detection: needs {anomaly_status['min_required']} sessions "
                            f"({anomaly_status['n_sessions']} recorded so far).")

                # ── Trend label ──────────────────────────────────────────────
                trend = "IMPROVING" if len(df) >= 2 and df["rehab_score"].iloc[-1] > df["rehab_score"].iloc[0] else "STABLE / NEEDS REVIEW"
                st.markdown(f"**Progress: {trend}**")

                # ── Trajectory ───────────────────────────────────────────────
                traj = predict_trajectory(df)
                fig = go.Figure()
                fig.add_scatter(x=df["session_number"], y=df["rom"], mode="lines+markers",
                                name="Actual ROM", line=dict(color="#22D3AA"))
                if not traj["not_enough_data"]:
                    future_x = [df["session_number"].iloc[-1] + i for i in range(1, len(traj["_y_future"]) + 1)]
                    fig.add_scatter(x=future_x, y=traj["_y_future"], mode="lines",
                                    name="Projected", line=dict(color="#F59E0B", dash="dash"))
                fig.update_layout(title=f"{p['patient_id']} — ROM & Score",
                                  plot_bgcolor="rgba(0,0,0,0)", paper_bgcolor="rgba(0,0,0,0)",
                                  font=dict(color="#E8EEF6"))
                fig.add_scatter(x=df["session_number"], y=df["rehab_score"], mode="lines+markers",
                                name="Rehab Score", line=dict(color="#3B82F6"))
                st.plotly_chart(fig, use_container_width=True)

                # ── Anomaly highlights ───────────────────────────────────────
                if anomaly_status["ready"] and "is_anomaly" in df.columns:
                    anomalous = df[df["is_anomaly"]]
                    if not anomalous.empty:
                        st.markdown("**🔴 AI-Flagged Sessions:**")
                        for _, row in anomalous.iterrows():
                            st.error(f"[{row['date'][:10]}] {row['exercise_name']} — "
                                     f"ROM {row['rom']}°, Score {row['rehab_score']}/100 "
                                     f"(anomaly score: {row['anomaly_score']})")

                # ── Review alerts ────────────────────────────────────────────
                alerts = db.get_alerts_for_patient(p["patient_id"])
                if alerts:
                    st.markdown("**Review Flags:**")
                    for a in alerts:
                        st.warning(f"[{a['date'][:10]}] {a['description']}")
                else:
                    st.success("No review flags.")

                # ── LLM clinical summary ─────────────────────────────────────
                if len(df) >= 2:
                    with st.spinner("Generating AI clinical summary…"):
                        summary = llm_summary(df, p["patient_id"])
                    st.info(f"🤖 **AI Clinical Summary:** {summary}")

                # ── FHIR export per patient ──────────────────────────────────
                fhir_json = sessions_to_fhir(df, p["patient_id"])
                st.download_button(
                    f"🔗 FHIR R4 JSON — {p['patient_id']}",
                    fhir_json,
                    file_name=f"rehabsense_{p['patient_id']}_fhir.json",
                    mime="application/json",
                    key=f"fhir_{p['patient_id']}",
                )

st.divider()
st.caption(
    "RehabSense AI is a hackathon prototype for assistive rehabilitation "
    "monitoring — not a diagnostic system or a substitute for professional "
    "clinical judgment. **Privacy:** All pose processing is on-device.\n"
    "Positioned as a Class I wellness/monitoring tool, not a diagnostic device."
)
